import { platformLocations } from "./locations";
import type { Job, ManpowerListing, Profile, Taxon } from "./domain";
export const id = (n: number) =>
  `00000000-0000-4000-8000-${String(n).padStart(12, "0")}`;
export const categoryNames = [
  "New Elevator Installation",
  "Elevator Erection",
  "Mechanical Installation",
  "Electrical Installation",
  "Wiring",
  "Testing",
  "Commissioning",
  "Testing & Commissioning",
  "Preventive Maintenance",
  "Breakdown Maintenance",
  "Repair",
  "Modernization",
  "Elevator Replacement",
  "Dismantling",
  "Shaft Survey",
  "Site Survey",
  "Quality Inspection",
  "Safety Inspection",
  "Door Installation",
  "Controller Installation",
  "Machine Installation",
  "Traction System Work",
  "Hydraulic Elevator Work",
  "Escalator Installation",
  "Escalator Maintenance",
  "Moving Walk Maintenance",
  "Civil Coordination",
  "Material Handling",
  "Helper / General Labour",
  "Supervisor Requirement",
  "Site Engineer Requirement",
];
export const roleNames = [
  "Elevator Technician",
  "Senior Elevator Technician",
  "Installation Technician",
  "Maintenance Technician",
  "Service Technician",
  "Modernization Technician",
  "Testing Engineer",
  "Commissioning Engineer",
  "Electrical Technician",
  "Electrician",
  "Mechanic",
  "Fitter",
  "Welder",
  "Helper",
  "Skilled Helper",
  "Supervisor",
  "Site Supervisor",
  "Site Engineer",
  "Safety Supervisor",
  "Project Engineer",
];
export const skillNames = [
  "Elevator installation",
  "Mechanical erection",
  "Electrical wiring",
  "Controller wiring",
  "Troubleshooting",
  "Preventive maintenance",
  "Breakdown maintenance",
  "Commissioning",
  "Alignment",
  "Guide rail installation",
  "Door installation",
  "Machine installation",
  "Traction system",
  "Hydraulic systems",
  "VVVF drives",
  "PLC/controller troubleshooting",
  "Shaft work",
  "Escalator servicing",
  "Welding",
  "Working at height",
  "Safety procedures",
];
export const categories: Taxon[] = categoryNames.map((name, i) => ({
  id: id(100 + i),
  name,
}));
export const roles: Taxon[] = roleNames.map((name, i) => ({
  id: id(200 + i),
  name,
}));
export const skills: Taxon[] = skillNames.map((name, i) => ({
  id: id(300 + i),
  name,
}));
export const profiles: Profile[] = [
  {
    id: id(1),
    kind: "COMPANY",
    name: "Apex Elevators Pvt. Ltd.",
    city: "Bengaluru",
    state: "Karnataka",
    bio: "Elevator installation and modernization teams serving residential and commercial projects across southern India.",
    experience: 14,
    primary_role: "Elevator installation",
    availability: "Accepting proposals",
    expected_rate: 0,
    verified: true,
    rating: 4.8,
    completed_count: 32,
  },
  {
    id: id(2),
    kind: "COMPANY",
    name: "Summit Lift Systems",
    city: "Mumbai",
    state: "Maharashtra",
    bio: "Independent elevator maintenance and commissioning specialists.",
    experience: 11,
    primary_role: "Maintenance & commissioning",
    availability: "Accepting proposals",
    expected_rate: 0,
    verified: true,
    rating: 4.7,
    completed_count: 24,
  },
  {
    id: id(3),
    kind: "VENDOR",
    name: "Vertex Lift Manpower Services",
    city: "Bengaluru",
    state: "Karnataka",
    bio: "Installation technicians, skilled helpers and supervisors. Teams available for residential tower installations with mobilization within five days.",
    experience: 9,
    primary_role: "Installation teams",
    availability: "Available in 5 days",
    expected_rate: 1500,
    verified: true,
    rating: 4.9,
    completed_count: 21,
    team_size: 28,
    brands: "KONE, Otis, Schindler, Johnson Lifts",
    travel: true,
    skills: [skills[0], skills[1], skills[19]],
  },
  {
    id: id(4),
    kind: "WORKER",
    name: "Arjun Kumar",
    city: "Bengaluru",
    state: "Karnataka",
    bio: "Installation technician with traction elevator experience. Comfortable with guide rail alignment, door installation and site safety coordination.",
    experience: 7,
    primary_role: "Installation Technician",
    availability: "Available now",
    expected_rate: 1600,
    verified: false,
    rating: 4.8,
    completed_count: 16,
    skills: [skills[0], skills[8], skills[10]],
  },
  {
    id: id(5),
    kind: "WORKER",
    name: "Priya Sharma",
    city: "Pune",
    state: "Maharashtra",
    bio: "Electrical technician experienced in controller wiring, VVVF drives and systematic fault diagnosis.",
    experience: 5,
    primary_role: "Electrical Technician",
    availability: "From 10 October",
    expected_rate: 1800,
    verified: false,
    rating: 4.9,
    completed_count: 12,
    skills: [skills[2], skills[3], skills[14]],
  },
  {
    id: id(6),
    kind: "VENDOR",
    name: "Precision Elevator Workforce",
    city: "Chennai",
    state: "Tamil Nadu",
    bio: "Maintenance and modernization teams serving Chennai and Hyderabad, with dedicated site supervisors.",
    experience: 12,
    primary_role: "Modernization & maintenance",
    availability: "Available in 7 days",
    expected_rate: 1700,
    verified: true,
    rating: 4.7,
    completed_count: 34,
    team_size: 42,
    brands: "Mitsubishi Electric, Fujitec, Thyssenkrupp",
    travel: true,
    skills: [skills[4], skills[5], skills[20]],
  },
];
const titles = [
  "Installation manpower — Whitefield residential towers",
  "Testing & commissioning — commercial lift project",
  "Preventive maintenance — residential portfolio",
  "Modernization team — hospital elevator upgrade",
  "Escalator installation — retail development",
  "Breakdown support — commercial office campus",
];
export const demoJobs: Job[] = platformLocations.map(({ city, state }, i) => ({
  id: id(1000 + i),
  owner_id: profiles[i % 2].id,
  title: titles[i],
  description:
    "Join an experienced site team delivering safe, reliable elevator systems. We are inviting qualified technicians and manpower partners for this project.",
  scope:
    i === 0
      ? "Mechanical erection and installation of six traction elevators across two residential towers. Includes guide rail alignment, landing doors, machine installation and coordination with the electrical team."
      : "Coordinate with the site supervisor, complete the assigned elevator work, follow lockout procedures and maintain daily work records. Handover includes testing documentation and a joint site inspection.",
  category_id: categories[[0, 7, 8, 11, 23, 9][i]].id,
  city,
  state,
  site_name: [
    "Whitefield residential towers",
    "Andheri business park",
    "Baner residences",
    "Gachibowli hospital",
    "OMR retail centre",
    "Noida office campus",
  ][i],
  start_date: `2026-10-${15 + i * 2}`,
  end_date: "2027-01-15",
  deadline: "2026-10-10",
  duration: i % 2 ? "6 weeks" : "3 months",
  shift: "Day shift · Monday–Saturday",
  hours: 8,
  rate_basis: "DAY",
  min_rate: 1200 + i * 100,
  max_rate: 1800 + i * 150,
  payment_terms: "Monthly payment within 15 days of approved attendance.",
  individuals: true,
  vendors: true,
  accommodation: i % 2 ? "NEGOTIABLE" : "YES",
  food: "NO",
  travel: "YES",
  ppe: "YES",
  tools: "YES",
  safety:
    "Site induction, fall protection and lockout/tagout procedures are mandatory. Work only under approved site permits.",
  status: "OPEN",
  created_at: `2026-09-${25 - i}T09:00:00Z`,
  profiles: profiles[i % 2],
  categories: categories[[0, 7, 8, 11, 23, 9][i]],
  job_roles: [
    {
      id: id(2000 + i * 3),
      role_id: roles[2].id,
      quantity: 6,
      min_experience: 3,
      filled: 0,
      worker_roles: roles[2],
    },
    {
      id: id(2001 + i * 3),
      role_id: roles[13].id,
      quantity: 8,
      min_experience: 0,
      filled: 0,
      worker_roles: roles[13],
    },
    {
      id: id(2002 + i * 3),
      role_id: roles[16].id,
      quantity: 1,
      min_experience: 5,
      filled: 0,
      worker_roles: roles[16],
    },
  ],
  job_skills: [
    { skills: skills[0] },
    { skills: skills[19] },
    { skills: skills[20] },
  ],
}));

const manpowerSeed: Array<{
  id: number;
  vendor: number;
  title: string;
  description: string;
  city: string;
  state: string;
  available: string;
  mobilization: number;
  travel: boolean;
  engagement: number;
  rate: ManpowerListing["rate_type"];
  min?: number;
  max?: number;
  roles: number[][];
  categories: number[];
  skills: number[];
}> = [
  {
    id: 6000,
    vendor: 2,
    title: "Installation & Commissioning Team Available — Bengaluru",
    description:
      "Experienced traction elevator installation team available for residential and commercial projects, from mechanical erection through testing and commissioning.",
    city: "Bengaluru",
    state: "Karnataka",
    available: "2026-10-12",
    mobilization: 3,
    travel: true,
    engagement: 30,
    rate: "NEGOTIATED" as const,
    roles: [
      [2, 6, 3, 9],
      [13, 8, 0, 5],
      [9, 2, 3, 10],
      [16, 1, 6, 15],
    ],
    categories: [0, 1, 3, 5, 6],
    skills: [0, 1, 2, 7, 9],
  },
  {
    id: 6001,
    vendor: 5,
    title: "Maintenance Technicians Available — Hyderabad",
    description:
      "Mobile preventive and breakdown maintenance technicians with controller troubleshooting experience for multi-site service portfolios.",
    city: "Hyderabad",
    state: "Telangana",
    available: "2026-10-15",
    mobilization: 5,
    travel: true,
    engagement: 60,
    rate: "DAY" as const,
    min: 1600,
    max: 2200,
    roles: [
      [3, 8, 3, 12],
      [4, 4, 2, 8],
      [15, 1, 7, 15],
    ],
    categories: [8, 9, 10],
    skills: [4, 5, 6, 14, 15],
  },
  {
    id: 6002,
    vendor: 5,
    title: "Modernization Team Available — Mumbai",
    description:
      "Modernization technicians and electrical specialists for controller upgrades, door systems and phased replacement work in occupied buildings.",
    city: "Mumbai",
    state: "Maharashtra",
    available: "2026-10-20",
    mobilization: 7,
    travel: true,
    engagement: 45,
    rate: "PROJECT" as const,
    min: 450000,
    max: 800000,
    roles: [
      [5, 5, 5, 15],
      [8, 3, 4, 12],
      [13, 4, 1, 6],
      [16, 1, 7, 18],
    ],
    categories: [11, 12, 18, 19],
    skills: [3, 10, 14, 15],
  },
  {
    id: 6003,
    vendor: 2,
    title: "Elevator Installation Crew — Pune",
    description:
      "Balanced installation crew for machine, guide rail and landing-door work with an experienced site supervisor and safety-trained helpers.",
    city: "Pune",
    state: "Maharashtra",
    available: "2026-10-18",
    mobilization: 4,
    travel: true,
    engagement: 30,
    rate: "SHIFT" as const,
    min: 1400,
    max: 2400,
    roles: [
      [2, 5, 3, 10],
      [13, 7, 0, 5],
      [16, 1, 6, 15],
    ],
    categories: [0, 2, 18, 20],
    skills: [0, 1, 9, 10, 11, 19],
  },
  {
    id: 6004,
    vendor: 5,
    title: "Testing & Commissioning Engineers — Chennai",
    description:
      "Testing and commissioning engineers available for pre-handover checks, controller tuning, safety verification and client demonstrations.",
    city: "Chennai",
    state: "Tamil Nadu",
    available: "2026-10-10",
    mobilization: 2,
    travel: false,
    engagement: 14,
    rate: "MONTH" as const,
    min: 52000,
    max: 78000,
    roles: [
      [6, 3, 5, 15],
      [7, 2, 5, 15],
      [8, 2, 4, 12],
    ],
    categories: [5, 6, 7, 16],
    skills: [2, 3, 4, 7, 14],
  },
];

export const demoManpowerListings: ManpowerListing[] = manpowerSeed.map(
  (listing, listingIndex) => ({
    id: id(listing.id),
    vendor_id: profiles[listing.vendor].id,
    title: listing.title,
    description: listing.description,
    city: listing.city,
    state: listing.state,
    available_from: listing.available,
    mobilization_days: listing.mobilization,
    willing_to_travel: listing.travel,
    minimum_engagement_days: listing.engagement,
    rate_type: listing.rate,
    minimum_rate: listing.min ?? null,
    maximum_rate: listing.max ?? null,
    currency: "INR",
    status: "ACTIVE",
    created_at: `2026-10-0${listingIndex + 1}T09:00:00Z`,
    updated_at: `2026-10-0${listingIndex + 1}T09:00:00Z`,
    profiles: profiles[listing.vendor],
    items: listing.roles.map(
      ([role, quantity, minimum, maximum], itemIndex) => ({
        id: id(6100 + listingIndex * 10 + itemIndex),
        worker_role_id: roles[role].id,
        quantity_available: quantity,
        minimum_experience_years: minimum,
        maximum_experience_years: maximum,
        worker_roles: roles[role],
      }),
    ),
    categories: listing.categories.map((category) => categories[category]),
    skills: listing.skills.map((skill) => skills[skill]),
  }),
);
